@host=https://localhost:7127

POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Camila",
    "LastName": "",
    "email": "camila@laura.com",
    "password": "camila123!"
}