@host=https://localhost:7127

GET {{host}}/dinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDQ3MjBhNy01ZGI4LTQyZDktYWMzOS1iNTRjMzA1NDVmZDIiLCJnaXZlbl9uYW1lIjoiQ2FtaWxhIiwiZmFtaWx5X25hbWUiOiJMYXVyYSIsImp0aSI6IjY2ODY0N2Y0LWFlNDktNDA5MS1hNGRhLTg0YTRmMjllOWM4MCIsImV4cCI6MTY4MTQ5MzM4NywiaXNzIjoiQ1JVRENoYWxsZW5nZSIsImF1ZCI6IkNSVURDaGFsbGVuZ2UifQ.UL6NsMKPeKf2dJQlU8wsQlCwOvLcanWfXwKzVqaEtq4
